sudo: required
services:
  - docker
before_install:
  - docker build -t dicker66/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true dicker66/docker-react npm run test -- --coverage
language: generic